import QtQuick 2.0
import QtQuick.Layouts 1.1

import "../controls" as Awesome

GridLayout {
    Awesome.Text { text: "fa_adjust"                ;  icon: awesome.icons.fa_adjust               ; }
    Awesome.Text { text: "fa_adn"                   ;  icon: awesome.icons.fa_adn                  ; }
    Awesome.Text { text: "fa_align_center"          ;  icon: awesome.icons.fa_align_center         ; }
    Awesome.Text { text: "fa_align_justify"         ;  icon: awesome.icons.fa_align_justify        ; }
    Awesome.Text { text: "fa_align_left"            ;  icon: awesome.icons.fa_align_left           ; }
    Awesome.Text { text: "fa_align_right"           ;  icon: awesome.icons.fa_align_right          ; }
    Awesome.Text { text: "fa_ambulance"             ;  icon: awesome.icons.fa_ambulance            ; }
    Awesome.Text { text: "fa_anchor"                ;  icon: awesome.icons.fa_anchor               ; }
    Awesome.Text { text: "fa_android"               ;  icon: awesome.icons.fa_android              ; }
    Awesome.Text { text: "fa_angle_double_down"     ;  icon: awesome.icons.fa_angle_double_down    ; }
    Awesome.Text { text: "fa_angle_double_left"     ;  icon: awesome.icons.fa_angle_double_left    ; }
    Awesome.Text { text: "fa_angle_double_right"    ;  icon: awesome.icons.fa_angle_double_right   ; }
    Awesome.Text { text: "fa_angle_double_up"       ;  icon: awesome.icons.fa_angle_double_up      ; }
    Awesome.Text { text: "fa_angle_down"            ;  icon: awesome.icons.fa_angle_down           ; }
    Awesome.Text { text: "fa_angle_left"            ;  icon: awesome.icons.fa_angle_left           ; }
    Awesome.Text { text: "fa_angle_right"           ;  icon: awesome.icons.fa_angle_right          ; }
    Awesome.Text { text: "fa_angle_up"              ;  icon: awesome.icons.fa_angle_up             ; }
    Awesome.Text { text: "fa_apple"                 ;  icon: awesome.icons.fa_apple                ; }
    Awesome.Text { text: "fa_archive"               ;  icon: awesome.icons.fa_archive              ; }
    Awesome.Text { text: "fa_arrow_circle_down"     ;  icon: awesome.icons.fa_arrow_circle_down    ; }
    Awesome.Text { text: "fa_arrow_circle_left"     ;  icon: awesome.icons.fa_arrow_circle_left    ; }
    Awesome.Text { text: "fa_arrow_circle_o_down"   ;  icon: awesome.icons.fa_arrow_circle_o_down  ; }
    Awesome.Text { text: "fa_arrow_circle_o_left"   ;  icon: awesome.icons.fa_arrow_circle_o_left  ; }
    Awesome.Text { text: "fa_arrow_circle_o_right"  ;  icon: awesome.icons.fa_arrow_circle_o_right ; }
    Awesome.Text { text: "fa_arrow_circle_o_up"     ;  icon: awesome.icons.fa_arrow_circle_o_up    ; }
    Awesome.Text { text: "fa_arrow_circle_right"    ;  icon: awesome.icons.fa_arrow_circle_right   ; }
    Awesome.Text { text: "fa_arrow_circle_up"       ;  icon: awesome.icons.fa_arrow_circle_up      ; }
    Awesome.Text { text: "fa_arrow_down"            ;  icon: awesome.icons.fa_arrow_down           ; }
    Awesome.Text { text: "fa_arrow_left"            ;  icon: awesome.icons.fa_arrow_left           ; }
    Awesome.Text { text: "fa_arrow_right"           ;  icon: awesome.icons.fa_arrow_right          ; }
    Awesome.Text { text: "fa_arrow_up"              ;  icon: awesome.icons.fa_arrow_up             ; }
    Awesome.Text { text: "fa_arrows"                ;  icon: awesome.icons.fa_arrows               ; }
    Awesome.Text { text: "fa_arrows_alt"            ;  icon: awesome.icons.fa_arrows_alt           ; }
    Awesome.Text { text: "fa_arrows_h"              ;  icon: awesome.icons.fa_arrows_h             ; }
    Awesome.Text { text: "fa_arrows_v"              ;  icon: awesome.icons.fa_arrows_v             ; }
    Awesome.Text { text: "fa_asterisk"              ;  icon: awesome.icons.fa_asterisk             ; }
    Awesome.Text { text: "fa_automobile"            ;  icon: awesome.icons.fa_automobile           ; }
    Awesome.Text { text: "fa_backward"              ;  icon: awesome.icons.fa_backward             ; }
    Awesome.Text { text: "fa_ban"                   ;  icon: awesome.icons.fa_ban                  ; }
    Awesome.Text { text: "fa_bank"                  ;  icon: awesome.icons.fa_bank                 ; }
    Awesome.Text { text: "fa_bar_chart_o"           ;  icon: awesome.icons.fa_bar_chart_o          ; }
    Awesome.Text { text: "fa_barcode"               ;  icon: awesome.icons.fa_barcode              ; }
    Awesome.Text { text: "fa_bars"                  ;  icon: awesome.icons.fa_bars                 ; }
    Awesome.Text { text: "fa_beer"                  ;  icon: awesome.icons.fa_beer                 ; }
    Awesome.Text { text: "fa_behance"               ;  icon: awesome.icons.fa_behance              ; }
    Awesome.Text { text: "fa_behance_square"        ;  icon: awesome.icons.fa_behance_square       ; }
    Awesome.Text { text: "fa_bell"                  ;  icon: awesome.icons.fa_bell                 ; }
    Awesome.Text { text: "fa_bell_o"                ;  icon: awesome.icons.fa_bell_o               ; }
    Awesome.Text { text: "fa_bitbucket"             ;  icon: awesome.icons.fa_bitbucket            ; }
    Awesome.Text { text: "fa_bitbucket_square"      ;  icon: awesome.icons.fa_bitbucket_square     ; }
    Awesome.Text { text: "fa_bitcoin"               ;  icon: awesome.icons.fa_bitcoin              ; }
    Awesome.Text { text: "fa_bold"                  ;  icon: awesome.icons.fa_bold                 ; }
    Awesome.Text { text: "fa_bolt"                  ;  icon: awesome.icons.fa_bolt                 ; }
    Awesome.Text { text: "fa_bomb"                  ;  icon: awesome.icons.fa_bomb                 ; }
    Awesome.Text { text: "fa_book"                  ;  icon: awesome.icons.fa_book                 ; }
    Awesome.Text { text: "fa_bookmark"              ;  icon: awesome.icons.fa_bookmark             ; }
    Awesome.Text { text: "fa_bookmark_o"            ;  icon: awesome.icons.fa_bookmark_o           ; }
    Awesome.Text { text: "fa_briefcase"             ;  icon: awesome.icons.fa_briefcase            ; }
    Awesome.Text { text: "fa_btc"                   ;  icon: awesome.icons.fa_btc                  ; }
    Awesome.Text { text: "fa_bug"                   ;  icon: awesome.icons.fa_bug                  ; }
    Awesome.Text { text: "fa_building"              ;  icon: awesome.icons.fa_building             ; }
    Awesome.Text { text: "fa_building_o"            ;  icon: awesome.icons.fa_building_o           ; }
    Awesome.Text { text: "fa_bullhorn"              ;  icon: awesome.icons.fa_bullhorn             ; }
    Awesome.Text { text: "fa_bullseye"              ;  icon: awesome.icons.fa_bullseye             ; }
    Awesome.Text { text: "fa_cab"                   ;  icon: awesome.icons.fa_cab                  ; }
    Awesome.Text { text: "fa_calendar"              ;  icon: awesome.icons.fa_calendar             ; }
    Awesome.Text { text: "fa_calendar_o"            ;  icon: awesome.icons.fa_calendar_o           ; }
    Awesome.Text { text: "fa_camera"                ;  icon: awesome.icons.fa_camera               ; }
    Awesome.Text { text: "fa_camera_retro"          ;  icon: awesome.icons.fa_camera_retro         ; }
    Awesome.Text { text: "fa_car"                   ;  icon: awesome.icons.fa_car                  ; }
    Awesome.Text { text: "fa_caret_down"            ;  icon: awesome.icons.fa_caret_down           ; }
    Awesome.Text { text: "fa_caret_left"            ;  icon: awesome.icons.fa_caret_left           ; }
    Awesome.Text { text: "fa_caret_right"           ;  icon: awesome.icons.fa_caret_right          ; }
    Awesome.Text { text: "fa_caret_square_o_down"   ;  icon: awesome.icons.fa_caret_square_o_down  ; }
    Awesome.Text { text: "fa_caret_square_o_left"   ;  icon: awesome.icons.fa_caret_square_o_left  ; }
    Awesome.Text { text: "fa_caret_square_o_right"  ;  icon: awesome.icons.fa_caret_square_o_right ; }
    Awesome.Text { text: "fa_caret_square_o_up"     ;  icon: awesome.icons.fa_caret_square_o_up    ; }
    Awesome.Text { text: "fa_caret_up"              ;  icon: awesome.icons.fa_caret_up             ; }
    Awesome.Text { text: "fa_certificate"           ;  icon: awesome.icons.fa_certificate          ; }
    Awesome.Text { text: "fa_chain"                 ;  icon: awesome.icons.fa_chain                ; }
    Awesome.Text { text: "fa_chain_broken"          ;  icon: awesome.icons.fa_chain_broken         ; }
    Awesome.Text { text: "fa_check"                 ;  icon: awesome.icons.fa_check                ; }
    Awesome.Text { text: "fa_check_circle"          ;  icon: awesome.icons.fa_check_circle         ; }
    Awesome.Text { text: "fa_check_circle_o"        ;  icon: awesome.icons.fa_check_circle_o       ; }
    Awesome.Text { text: "fa_check_square"          ;  icon: awesome.icons.fa_check_square         ; }
    Awesome.Text { text: "fa_check_square_o"        ;  icon: awesome.icons.fa_check_square_o       ; }
    Awesome.Text { text: "fa_chevron_circle_down"   ;  icon: awesome.icons.fa_chevron_circle_down  ; }
    Awesome.Text { text: "fa_chevron_circle_left"   ;  icon: awesome.icons.fa_chevron_circle_left  ; }
    Awesome.Text { text: "fa_chevron_circle_right"  ;  icon: awesome.icons.fa_chevron_circle_right ; }
    Awesome.Text { text: "fa_chevron_circle_up"     ;  icon: awesome.icons.fa_chevron_circle_up    ; }
    Awesome.Text { text: "fa_chevron_down"          ;  icon: awesome.icons.fa_chevron_down         ; }
    Awesome.Text { text: "fa_chevron_left"          ;  icon: awesome.icons.fa_chevron_left         ; }
    Awesome.Text { text: "fa_chevron_right"         ;  icon: awesome.icons.fa_chevron_right        ; }
    Awesome.Text { text: "fa_chevron_up"            ;  icon: awesome.icons.fa_chevron_up           ; }
    Awesome.Text { text: "fa_child"                 ;  icon: awesome.icons.fa_child                ; }
    Awesome.Text { text: "fa_circle"                ;  icon: awesome.icons.fa_circle               ; }
    Awesome.Text { text: "fa_circle_o"              ;  icon: awesome.icons.fa_circle_o             ; }
    Awesome.Text { text: "fa_circle_o_notch"        ;  icon: awesome.icons.fa_circle_o_notch       ; }
    Awesome.Text { text: "fa_circle_thin"           ;  icon: awesome.icons.fa_circle_thin          ; }
    Awesome.Text { text: "fa_clipboard"             ;  icon: awesome.icons.fa_clipboard            ; }
    Awesome.Text { text: "fa_clock_o"               ;  icon: awesome.icons.fa_clock_o              ; }
    Awesome.Text { text: "fa_cloud"                 ;  icon: awesome.icons.fa_cloud                ; }
    Awesome.Text { text: "fa_cloud_download"        ;  icon: awesome.icons.fa_cloud_download       ; }
    Awesome.Text { text: "fa_cloud_upload"          ;  icon: awesome.icons.fa_cloud_upload         ; }
    Awesome.Text { text: "fa_cny"                   ;  icon: awesome.icons.fa_cny                  ; }
    Awesome.Text { text: "fa_code"                  ;  icon: awesome.icons.fa_code                 ; }
    Awesome.Text { text: "fa_code_fork"             ;  icon: awesome.icons.fa_code_fork            ; }
    Awesome.Text { text: "fa_codepen"               ;  icon: awesome.icons.fa_codepen              ; }
    Awesome.Text { text: "fa_coffee"                ;  icon: awesome.icons.fa_coffee               ; }
    Awesome.Text { text: "fa_cog"                   ;  icon: awesome.icons.fa_cog                  ; }
    Awesome.Text { text: "fa_cogs"                  ;  icon: awesome.icons.fa_cogs                 ; }
    Awesome.Text { text: "fa_columns"               ;  icon: awesome.icons.fa_columns              ; }
    Awesome.Text { text: "fa_comment"               ;  icon: awesome.icons.fa_comment              ; }
    Awesome.Text { text: "fa_comment_o"             ;  icon: awesome.icons.fa_comment_o            ; }
    Awesome.Text { text: "fa_comments"              ;  icon: awesome.icons.fa_comments             ; }
    Awesome.Text { text: "fa_comments_o"            ;  icon: awesome.icons.fa_comments_o           ; }
    Awesome.Text { text: "fa_compass"               ;  icon: awesome.icons.fa_compass              ; }
    Awesome.Text { text: "fa_compress"              ;  icon: awesome.icons.fa_compress             ; }
    Awesome.Text { text: "fa_copy"                  ;  icon: awesome.icons.fa_copy                 ; }
    Awesome.Text { text: "fa_credit_card"           ;  icon: awesome.icons.fa_credit_card          ; }
    Awesome.Text { text: "fa_crop"                  ;  icon: awesome.icons.fa_crop                 ; }
    Awesome.Text { text: "fa_crosshairs"            ;  icon: awesome.icons.fa_crosshairs           ; }
    Awesome.Text { text: "fa_css3"                  ;  icon: awesome.icons.fa_css3                 ; }
    Awesome.Text { text: "fa_cube"                  ;  icon: awesome.icons.fa_cube                 ; }
    Awesome.Text { text: "fa_cubes"                 ;  icon: awesome.icons.fa_cubes                ; }
    Awesome.Text { text: "fa_cut"                   ;  icon: awesome.icons.fa_cut                  ; }
    Awesome.Text { text: "fa_cutlery"               ;  icon: awesome.icons.fa_cutlery              ; }
    Awesome.Text { text: "fa_dashboard"             ;  icon: awesome.icons.fa_dashboard            ; }
    Awesome.Text { text: "fa_database"              ;  icon: awesome.icons.fa_database             ; }
    Awesome.Text { text: "fa_dedent"                ;  icon: awesome.icons.fa_dedent               ; }
    Awesome.Text { text: "fa_delicious"             ;  icon: awesome.icons.fa_delicious            ; }
    Awesome.Text { text: "fa_desktop"               ;  icon: awesome.icons.fa_desktop              ; }
    Awesome.Text { text: "fa_deviantart"            ;  icon: awesome.icons.fa_deviantart           ; }
    Awesome.Text { text: "fa_digg"                  ;  icon: awesome.icons.fa_digg                 ; }
    Awesome.Text { text: "fa_dollar"                ;  icon: awesome.icons.fa_dollar               ; }
    Awesome.Text { text: "fa_dot_circle_o"          ;  icon: awesome.icons.fa_dot_circle_o         ; }
    Awesome.Text { text: "fa_download"              ;  icon: awesome.icons.fa_download             ; }
    Awesome.Text { text: "fa_dribbble"              ;  icon: awesome.icons.fa_dribbble             ; }
    Awesome.Text { text: "fa_dropbox"               ;  icon: awesome.icons.fa_dropbox              ; }
    Awesome.Text { text: "fa_drupal"                ;  icon: awesome.icons.fa_drupal               ; }
    Awesome.Text { text: "fa_edit"                  ;  icon: awesome.icons.fa_edit                 ; }
    Awesome.Text { text: "fa_eject"                 ;  icon: awesome.icons.fa_eject                ; }
    Awesome.Text { text: "fa_ellipsis_h"            ;  icon: awesome.icons.fa_ellipsis_h           ; }
    Awesome.Text { text: "fa_ellipsis_v"            ;  icon: awesome.icons.fa_ellipsis_v           ; }
    Awesome.Text { text: "fa_empire"                ;  icon: awesome.icons.fa_empire               ; }
    Awesome.Text { text: "fa_envelope"              ;  icon: awesome.icons.fa_envelope             ; }
    Awesome.Text { text: "fa_envelope_o"            ;  icon: awesome.icons.fa_envelope_o           ; }
    Awesome.Text { text: "fa_envelope_square"       ;  icon: awesome.icons.fa_envelope_square      ; }
    Awesome.Text { text: "fa_eraser"                ;  icon: awesome.icons.fa_eraser               ; }
    Awesome.Text { text: "fa_eur"                   ;  icon: awesome.icons.fa_eur                  ; }
    Awesome.Text { text: "fa_euro"                  ;  icon: awesome.icons.fa_euro                 ; }
    Awesome.Text { text: "fa_exchange"              ;  icon: awesome.icons.fa_exchange             ; }
    Awesome.Text { text: "fa_exclamation"           ;  icon: awesome.icons.fa_exclamation          ; }
    Awesome.Text { text: "fa_exclamation_circle"    ;  icon: awesome.icons.fa_exclamation_circle   ; }
    Awesome.Text { text: "fa_exclamation_triangle"  ;  icon: awesome.icons.fa_exclamation_triangle ; }
    Awesome.Text { text: "fa_expand"                ;  icon: awesome.icons.fa_expand               ; }
    Awesome.Text { text: "fa_external_link"         ;  icon: awesome.icons.fa_external_link        ; }
    Awesome.Text { text: "fa_external_link_square"  ;  icon: awesome.icons.fa_external_link_square ; }
    Awesome.Text { text: "fa_eye"                   ;  icon: awesome.icons.fa_eye                  ; }
    Awesome.Text { text: "fa_eye_slash"             ;  icon: awesome.icons.fa_eye_slash            ; }
    Awesome.Text { text: "fa_facebook"              ;  icon: awesome.icons.fa_facebook             ; }
    Awesome.Text { text: "fa_facebook_square"       ;  icon: awesome.icons.fa_facebook_square      ; }
    Awesome.Text { text: "fa_fast_backward"         ;  icon: awesome.icons.fa_fast_backward        ; }
    Awesome.Text { text: "fa_fast_forward"          ;  icon: awesome.icons.fa_fast_forward         ; }
    Awesome.Text { text: "fa_fax"                   ;  icon: awesome.icons.fa_fax                  ; }
    Awesome.Text { text: "fa_female"                ;  icon: awesome.icons.fa_female               ; }
    Awesome.Text { text: "fa_fighter_jet"           ;  icon: awesome.icons.fa_fighter_jet          ; }
    Awesome.Text { text: "fa_file"                  ;  icon: awesome.icons.fa_file                 ; }
    Awesome.Text { text: "fa_file_archive_o"        ;  icon: awesome.icons.fa_file_archive_o       ; }
    Awesome.Text { text: "fa_file_audio_o"          ;  icon: awesome.icons.fa_file_audio_o         ; }
    Awesome.Text { text: "fa_file_code_o"           ;  icon: awesome.icons.fa_file_code_o          ; }
    Awesome.Text { text: "fa_file_excel_o"          ;  icon: awesome.icons.fa_file_excel_o         ; }
    Awesome.Text { text: "fa_file_image_o"          ;  icon: awesome.icons.fa_file_image_o         ; }
    Awesome.Text { text: "fa_file_movie_o"          ;  icon: awesome.icons.fa_file_movie_o         ; }
    Awesome.Text { text: "fa_file_o"                ;  icon: awesome.icons.fa_file_o               ; }
    Awesome.Text { text: "fa_file_pdf_o"            ;  icon: awesome.icons.fa_file_pdf_o           ; }
    Awesome.Text { text: "fa_file_photo_o"          ;  icon: awesome.icons.fa_file_photo_o         ; }
    Awesome.Text { text: "fa_file_picture_o"        ;  icon: awesome.icons.fa_file_picture_o       ; }
    Awesome.Text { text: "fa_file_powerpoint_o"     ;  icon: awesome.icons.fa_file_powerpoint_o    ; }
    Awesome.Text { text: "fa_file_sound_o"          ;  icon: awesome.icons.fa_file_sound_o         ; }
    Awesome.Text { text: "fa_file_text"             ;  icon: awesome.icons.fa_file_text            ; }
    Awesome.Text { text: "fa_file_text_o"           ;  icon: awesome.icons.fa_file_text_o          ; }
    Awesome.Text { text: "fa_file_video_o"          ;  icon: awesome.icons.fa_file_video_o         ; }
    Awesome.Text { text: "fa_file_word_o"           ;  icon: awesome.icons.fa_file_word_o          ; }
    Awesome.Text { text: "fa_file_zip_o"            ;  icon: awesome.icons.fa_file_zip_o           ; }
    Awesome.Text { text: "fa_files_o"               ;  icon: awesome.icons.fa_files_o              ; }
    Awesome.Text { text: "fa_film"                  ;  icon: awesome.icons.fa_film                 ; }
    Awesome.Text { text: "fa_filter"                ;  icon: awesome.icons.fa_filter               ; }
    Awesome.Text { text: "fa_fire"                  ;  icon: awesome.icons.fa_fire                 ; }
    Awesome.Text { text: "fa_fire_extinguisher"     ;  icon: awesome.icons.fa_fire_extinguisher    ; }
    Awesome.Text { text: "fa_flag"                  ;  icon: awesome.icons.fa_flag                 ; }
    Awesome.Text { text: "fa_flag_checkered"        ;  icon: awesome.icons.fa_flag_checkered       ; }
    Awesome.Text { text: "fa_flag_o"                ;  icon: awesome.icons.fa_flag_o               ; }
    Awesome.Text { text: "fa_flash"                 ;  icon: awesome.icons.fa_flash                ; }
    Awesome.Text { text: "fa_flask"                 ;  icon: awesome.icons.fa_flask                ; }
    Awesome.Text { text: "fa_flickr"                ;  icon: awesome.icons.fa_flickr               ; }
    Awesome.Text { text: "fa_floppy_o"              ;  icon: awesome.icons.fa_floppy_o             ; }
    Awesome.Text { text: "fa_folder"                ;  icon: awesome.icons.fa_folder               ; }
    Awesome.Text { text: "fa_folder_o"              ;  icon: awesome.icons.fa_folder_o             ; }
    Awesome.Text { text: "fa_folder_open"           ;  icon: awesome.icons.fa_folder_open          ; }
    Awesome.Text { text: "fa_folder_open_o"         ;  icon: awesome.icons.fa_folder_open_o        ; }
    Awesome.Text { text: "fa_font"                  ;  icon: awesome.icons.fa_font                 ; }
    Awesome.Text { text: "fa_forward"               ;  icon: awesome.icons.fa_forward              ; }
    Awesome.Text { text: "fa_foursquare"            ;  icon: awesome.icons.fa_foursquare           ; }
    Awesome.Text { text: "fa_frown_o"               ;  icon: awesome.icons.fa_frown_o              ; }
    Awesome.Text { text: "fa_gamepad"               ;  icon: awesome.icons.fa_gamepad              ; }
    Awesome.Text { text: "fa_gavel"                 ;  icon: awesome.icons.fa_gavel                ; }
    Awesome.Text { text: "fa_gbp"                   ;  icon: awesome.icons.fa_gbp                  ; }
    Awesome.Text { text: "fa_ge"                    ;  icon: awesome.icons.fa_ge                   ; }
    Awesome.Text { text: "fa_gear"                  ;  icon: awesome.icons.fa_gear                 ; }
    Awesome.Text { text: "fa_gears"                 ;  icon: awesome.icons.fa_gears                ; }
    Awesome.Text { text: "fa_gift"                  ;  icon: awesome.icons.fa_gift                 ; }
    Awesome.Text { text: "fa_git"                   ;  icon: awesome.icons.fa_git                  ; }
    Awesome.Text { text: "fa_git_square"            ;  icon: awesome.icons.fa_git_square           ; }
    Awesome.Text { text: "fa_github"                ;  icon: awesome.icons.fa_github               ; }
    Awesome.Text { text: "fa_github_alt"            ;  icon: awesome.icons.fa_github_alt           ; }
    Awesome.Text { text: "fa_github_square"         ;  icon: awesome.icons.fa_github_square        ; }
    Awesome.Text { text: "fa_gittip"                ;  icon: awesome.icons.fa_gittip               ; }
    Awesome.Text { text: "fa_glass"                 ;  icon: awesome.icons.fa_glass                ; }
    Awesome.Text { text: "fa_globe"                 ;  icon: awesome.icons.fa_globe                ; }
    Awesome.Text { text: "fa_google"                ;  icon: awesome.icons.fa_google               ; }
    Awesome.Text { text: "fa_google_plus"           ;  icon: awesome.icons.fa_google_plus          ; }
    Awesome.Text { text: "fa_google_plus_square"    ;  icon: awesome.icons.fa_google_plus_square   ; }
    Awesome.Text { text: "fa_graduation_cap"        ;  icon: awesome.icons.fa_graduation_cap       ; }
    Awesome.Text { text: "fa_group"                 ;  icon: awesome.icons.fa_group                ; }
    Awesome.Text { text: "fa_h_square"              ;  icon: awesome.icons.fa_h_square             ; }
    Awesome.Text { text: "fa_hacker_news"           ;  icon: awesome.icons.fa_hacker_news          ; }
    Awesome.Text { text: "fa_hand_o_down"           ;  icon: awesome.icons.fa_hand_o_down          ; }
    Awesome.Text { text: "fa_hand_o_left"           ;  icon: awesome.icons.fa_hand_o_left          ; }
    Awesome.Text { text: "fa_hand_o_right"          ;  icon: awesome.icons.fa_hand_o_right         ; }
    Awesome.Text { text: "fa_hand_o_up"             ;  icon: awesome.icons.fa_hand_o_up            ; }
    Awesome.Text { text: "fa_hdd_o"                 ;  icon: awesome.icons.fa_hdd_o                ; }
    Awesome.Text { text: "fa_header"                ;  icon: awesome.icons.fa_header               ; }
    Awesome.Text { text: "fa_headphones"            ;  icon: awesome.icons.fa_headphones           ; }
    Awesome.Text { text: "fa_heart"                 ;  icon: awesome.icons.fa_heart                ; }
    Awesome.Text { text: "fa_heart_o"               ;  icon: awesome.icons.fa_heart_o              ; }
    Awesome.Text { text: "fa_history"               ;  icon: awesome.icons.fa_history              ; }
    Awesome.Text { text: "fa_home"                  ;  icon: awesome.icons.fa_home                 ; }
    Awesome.Text { text: "fa_hospital_o"            ;  icon: awesome.icons.fa_hospital_o           ; }
    Awesome.Text { text: "fa_html5"                 ;  icon: awesome.icons.fa_html5                ; }
    Awesome.Text { text: "fa_image"                 ;  icon: awesome.icons.fa_image                ; }
    Awesome.Text { text: "fa_inbox"                 ;  icon: awesome.icons.fa_inbox                ; }
    Awesome.Text { text: "fa_indent"                ;  icon: awesome.icons.fa_indent               ; }
    Awesome.Text { text: "fa_info"                  ;  icon: awesome.icons.fa_info                 ; }
    Awesome.Text { text: "fa_info_circle"           ;  icon: awesome.icons.fa_info_circle          ; }
    Awesome.Text { text: "fa_inr"                   ;  icon: awesome.icons.fa_inr                  ; }
    Awesome.Text { text: "fa_instagram"             ;  icon: awesome.icons.fa_instagram            ; }
    Awesome.Text { text: "fa_institution"           ;  icon: awesome.icons.fa_institution          ; }
    Awesome.Text { text: "fa_italic"                ;  icon: awesome.icons.fa_italic               ; }
    Awesome.Text { text: "fa_joomla"                ;  icon: awesome.icons.fa_joomla               ; }
    Awesome.Text { text: "fa_jpy"                   ;  icon: awesome.icons.fa_jpy                  ; }
    Awesome.Text { text: "fa_jsfiddle"              ;  icon: awesome.icons.fa_jsfiddle             ; }
    Awesome.Text { text: "fa_key"                   ;  icon: awesome.icons.fa_key                  ; }
    Awesome.Text { text: "fa_keyboard_o"            ;  icon: awesome.icons.fa_keyboard_o           ; }
    Awesome.Text { text: "fa_krw"                   ;  icon: awesome.icons.fa_krw                  ; }
    Awesome.Text { text: "fa_language"              ;  icon: awesome.icons.fa_language             ; }
    Awesome.Text { text: "fa_laptop"                ;  icon: awesome.icons.fa_laptop               ; }
    Awesome.Text { text: "fa_leaf"                  ;  icon: awesome.icons.fa_leaf                 ; }
    Awesome.Text { text: "fa_legal"                 ;  icon: awesome.icons.fa_legal                ; }
    Awesome.Text { text: "fa_lemon_o"               ;  icon: awesome.icons.fa_lemon_o              ; }
    Awesome.Text { text: "fa_level_down"            ;  icon: awesome.icons.fa_level_down           ; }
    Awesome.Text { text: "fa_level_up"              ;  icon: awesome.icons.fa_level_up             ; }
    Awesome.Text { text: "fa_life_bouy"             ;  icon: awesome.icons.fa_life_bouy            ; }
    Awesome.Text { text: "fa_life_ring"             ;  icon: awesome.icons.fa_life_ring            ; }
    Awesome.Text { text: "fa_life_saver"            ;  icon: awesome.icons.fa_life_saver           ; }
    Awesome.Text { text: "fa_lightbulb_o"           ;  icon: awesome.icons.fa_lightbulb_o          ; }
    Awesome.Text { text: "fa_link"                  ;  icon: awesome.icons.fa_link                 ; }
    Awesome.Text { text: "fa_linkedin"              ;  icon: awesome.icons.fa_linkedin             ; }
    Awesome.Text { text: "fa_linkedin_square"       ;  icon: awesome.icons.fa_linkedin_square      ; }
    Awesome.Text { text: "fa_linux"                 ;  icon: awesome.icons.fa_linux                ; }
    Awesome.Text { text: "fa_list"                  ;  icon: awesome.icons.fa_list                 ; }
    Awesome.Text { text: "fa_list_alt"              ;  icon: awesome.icons.fa_list_alt             ; }
    Awesome.Text { text: "fa_list_ol"               ;  icon: awesome.icons.fa_list_ol              ; }
    Awesome.Text { text: "fa_list_ul"               ;  icon: awesome.icons.fa_list_ul              ; }
    Awesome.Text { text: "fa_location_arrow"        ;  icon: awesome.icons.fa_location_arrow       ; }
    Awesome.Text { text: "fa_lock"                  ;  icon: awesome.icons.fa_lock                 ; }
    Awesome.Text { text: "fa_long_arrow_down"       ;  icon: awesome.icons.fa_long_arrow_down      ; }
    Awesome.Text { text: "fa_long_arrow_left"       ;  icon: awesome.icons.fa_long_arrow_left      ; }
    Awesome.Text { text: "fa_long_arrow_right"      ;  icon: awesome.icons.fa_long_arrow_right     ; }
    Awesome.Text { text: "fa_long_arrow_up"         ;  icon: awesome.icons.fa_long_arrow_up        ; }
    Awesome.Text { text: "fa_magic"                 ;  icon: awesome.icons.fa_magic                ; }
    Awesome.Text { text: "fa_magnet"                ;  icon: awesome.icons.fa_magnet               ; }
    Awesome.Text { text: "fa_mail_forward"          ;  icon: awesome.icons.fa_mail_forward         ; }
    Awesome.Text { text: "fa_mail_reply"            ;  icon: awesome.icons.fa_mail_reply           ; }
    Awesome.Text { text: "fa_mail_reply_all"        ;  icon: awesome.icons.fa_mail_reply_all       ; }
    Awesome.Text { text: "fa_male"                  ;  icon: awesome.icons.fa_male                 ; }
    Awesome.Text { text: "fa_map_marker"            ;  icon: awesome.icons.fa_map_marker           ; }
    Awesome.Text { text: "fa_maxcdn"                ;  icon: awesome.icons.fa_maxcdn               ; }
    Awesome.Text { text: "fa_medkit"                ;  icon: awesome.icons.fa_medkit               ; }
    Awesome.Text { text: "fa_meh_o"                 ;  icon: awesome.icons.fa_meh_o                ; }
    Awesome.Text { text: "fa_microphone"            ;  icon: awesome.icons.fa_microphone           ; }
    Awesome.Text { text: "fa_microphone_slash"      ;  icon: awesome.icons.fa_microphone_slash     ; }
    Awesome.Text { text: "fa_minus"                 ;  icon: awesome.icons.fa_minus                ; }
    Awesome.Text { text: "fa_minus_circle"          ;  icon: awesome.icons.fa_minus_circle         ; }
    Awesome.Text { text: "fa_minus_square"          ;  icon: awesome.icons.fa_minus_square         ; }
    Awesome.Text { text: "fa_minus_square_o"        ;  icon: awesome.icons.fa_minus_square_o       ; }
    Awesome.Text { text: "fa_mobile"                ;  icon: awesome.icons.fa_mobile               ; }
    Awesome.Text { text: "fa_mobile_phone"          ;  icon: awesome.icons.fa_mobile_phone         ; }
    Awesome.Text { text: "fa_money"                 ;  icon: awesome.icons.fa_money                ; }
    Awesome.Text { text: "fa_moon_o"                ;  icon: awesome.icons.fa_moon_o               ; }
    Awesome.Text { text: "fa_mortar_board"          ;  icon: awesome.icons.fa_mortar_board         ; }
    Awesome.Text { text: "fa_music"                 ;  icon: awesome.icons.fa_music                ; }
    Awesome.Text { text: "fa_navicon"               ;  icon: awesome.icons.fa_navicon              ; }
    Awesome.Text { text: "fa_openid"                ;  icon: awesome.icons.fa_openid               ; }
    Awesome.Text { text: "fa_outdent"               ;  icon: awesome.icons.fa_outdent              ; }
    Awesome.Text { text: "fa_pagelines"             ;  icon: awesome.icons.fa_pagelines            ; }
    Awesome.Text { text: "fa_paper_plane"           ;  icon: awesome.icons.fa_paper_plane          ; }
    Awesome.Text { text: "fa_paper_plane_o"         ;  icon: awesome.icons.fa_paper_plane_o        ; }
    Awesome.Text { text: "fa_paperclip"             ;  icon: awesome.icons.fa_paperclip            ; }
    Awesome.Text { text: "fa_paragraph"             ;  icon: awesome.icons.fa_paragraph            ; }
    Awesome.Text { text: "fa_paste"                 ;  icon: awesome.icons.fa_paste                ; }
    Awesome.Text { text: "fa_pause"                 ;  icon: awesome.icons.fa_pause                ; }
    Awesome.Text { text: "fa_paw"                   ;  icon: awesome.icons.fa_paw                  ; }
    Awesome.Text { text: "fa_pencil"                ;  icon: awesome.icons.fa_pencil               ; }
    Awesome.Text { text: "fa_pencil_square"         ;  icon: awesome.icons.fa_pencil_square        ; }
    Awesome.Text { text: "fa_pencil_square_o"       ;  icon: awesome.icons.fa_pencil_square_o      ; }
    Awesome.Text { text: "fa_phone"                 ;  icon: awesome.icons.fa_phone                ; }
    Awesome.Text { text: "fa_phone_square"          ;  icon: awesome.icons.fa_phone_square         ; }
    Awesome.Text { text: "fa_photo"                 ;  icon: awesome.icons.fa_photo                ; }
    Awesome.Text { text: "fa_picture_o"             ;  icon: awesome.icons.fa_picture_o            ; }
    Awesome.Text { text: "fa_pied_piper"            ;  icon: awesome.icons.fa_pied_piper           ; }
    Awesome.Text { text: "fa_pied_piper_alt"        ;  icon: awesome.icons.fa_pied_piper_alt       ; }
    Awesome.Text { text: "fa_pied_piper_square"     ;  icon: awesome.icons.fa_pied_piper_square    ; }
    Awesome.Text { text: "fa_pinterest"             ;  icon: awesome.icons.fa_pinterest            ; }
    Awesome.Text { text: "fa_pinterest_square"      ;  icon: awesome.icons.fa_pinterest_square     ; }
    Awesome.Text { text: "fa_plane"                 ;  icon: awesome.icons.fa_plane                ; }
    Awesome.Text { text: "fa_play"                  ;  icon: awesome.icons.fa_play                 ; }
    Awesome.Text { text: "fa_play_circle"           ;  icon: awesome.icons.fa_play_circle          ; }
    Awesome.Text { text: "fa_play_circle_o"         ;  icon: awesome.icons.fa_play_circle_o        ; }
    Awesome.Text { text: "fa_plus"                  ;  icon: awesome.icons.fa_plus                 ; }
    Awesome.Text { text: "fa_plus_circle"           ;  icon: awesome.icons.fa_plus_circle          ; }
    Awesome.Text { text: "fa_plus_square"           ;  icon: awesome.icons.fa_plus_square          ; }
    Awesome.Text { text: "fa_plus_square_o"         ;  icon: awesome.icons.fa_plus_square_o        ; }
    Awesome.Text { text: "fa_power_off"             ;  icon: awesome.icons.fa_power_off            ; }
    Awesome.Text { text: "fa_print"                 ;  icon: awesome.icons.fa_print                ; }
    Awesome.Text { text: "fa_puzzle_piece"          ;  icon: awesome.icons.fa_puzzle_piece         ; }
    Awesome.Text { text: "fa_qq"                    ;  icon: awesome.icons.fa_qq                   ; }
    Awesome.Text { text: "fa_qrcode"                ;  icon: awesome.icons.fa_qrcode               ; }
    Awesome.Text { text: "fa_question"              ;  icon: awesome.icons.fa_question             ; }
    Awesome.Text { text: "fa_question_circle"       ;  icon: awesome.icons.fa_question_circle      ; }
    Awesome.Text { text: "fa_quote_left"            ;  icon: awesome.icons.fa_quote_left           ; }
    Awesome.Text { text: "fa_quote_right"           ;  icon: awesome.icons.fa_quote_right          ; }
    Awesome.Text { text: "fa_ra"                    ;  icon: awesome.icons.fa_ra                   ; }
    Awesome.Text { text: "fa_random"                ;  icon: awesome.icons.fa_random               ; }
    Awesome.Text { text: "fa_rebel"                 ;  icon: awesome.icons.fa_rebel                ; }
    Awesome.Text { text: "fa_recycle"               ;  icon: awesome.icons.fa_recycle              ; }
    Awesome.Text { text: "fa_reddit"                ;  icon: awesome.icons.fa_reddit               ; }
    Awesome.Text { text: "fa_reddit_square"         ;  icon: awesome.icons.fa_reddit_square        ; }
    Awesome.Text { text: "fa_refresh"               ;  icon: awesome.icons.fa_refresh              ; }
    Awesome.Text { text: "fa_renren"                ;  icon: awesome.icons.fa_renren               ; }
    Awesome.Text { text: "fa_reorder"               ;  icon: awesome.icons.fa_reorder              ; }
    Awesome.Text { text: "fa_repeat"                ;  icon: awesome.icons.fa_repeat               ; }
    Awesome.Text { text: "fa_reply"                 ;  icon: awesome.icons.fa_reply                ; }
    Awesome.Text { text: "fa_reply_all"             ;  icon: awesome.icons.fa_reply_all            ; }
    Awesome.Text { text: "fa_retweet"               ;  icon: awesome.icons.fa_retweet              ; }
    Awesome.Text { text: "fa_rmb"                   ;  icon: awesome.icons.fa_rmb                  ; }
    Awesome.Text { text: "fa_road"                  ;  icon: awesome.icons.fa_road                 ; }
    Awesome.Text { text: "fa_rocket"                ;  icon: awesome.icons.fa_rocket               ; }
    Awesome.Text { text: "fa_rotate_left"           ;  icon: awesome.icons.fa_rotate_left          ; }
    Awesome.Text { text: "fa_rotate_right"          ;  icon: awesome.icons.fa_rotate_right         ; }
    Awesome.Text { text: "fa_rouble"                ;  icon: awesome.icons.fa_rouble               ; }
    Awesome.Text { text: "fa_rss"                   ;  icon: awesome.icons.fa_rss                  ; }
    Awesome.Text { text: "fa_rss_square"            ;  icon: awesome.icons.fa_rss_square           ; }
    Awesome.Text { text: "fa_rub"                   ;  icon: awesome.icons.fa_rub                  ; }
    Awesome.Text { text: "fa_ruble"                 ;  icon: awesome.icons.fa_ruble                ; }
    Awesome.Text { text: "fa_rupee"                 ;  icon: awesome.icons.fa_rupee                ; }
    Awesome.Text { text: "fa_save"                  ;  icon: awesome.icons.fa_save                 ; }
    Awesome.Text { text: "fa_scissors"              ;  icon: awesome.icons.fa_scissors             ; }
    Awesome.Text { text: "fa_search"                ;  icon: awesome.icons.fa_search               ; }
    Awesome.Text { text: "fa_search_minus"          ;  icon: awesome.icons.fa_search_minus         ; }
    Awesome.Text { text: "fa_search_plus"           ;  icon: awesome.icons.fa_search_plus          ; }
    Awesome.Text { text: "fa_send"                  ;  icon: awesome.icons.fa_send                 ; }
    Awesome.Text { text: "fa_send_o"                ;  icon: awesome.icons.fa_send_o               ; }
    Awesome.Text { text: "fa_share"                 ;  icon: awesome.icons.fa_share                ; }
    Awesome.Text { text: "fa_share_alt"             ;  icon: awesome.icons.fa_share_alt            ; }
    Awesome.Text { text: "fa_share_alt_square"      ;  icon: awesome.icons.fa_share_alt_square     ; }
    Awesome.Text { text: "fa_share_square"          ;  icon: awesome.icons.fa_share_square         ; }
    Awesome.Text { text: "fa_share_square_o"        ;  icon: awesome.icons.fa_share_square_o       ; }
    Awesome.Text { text: "fa_shield"                ;  icon: awesome.icons.fa_shield               ; }
    Awesome.Text { text: "fa_shopping_cart"         ;  icon: awesome.icons.fa_shopping_cart        ; }
    Awesome.Text { text: "fa_sign_in"               ;  icon: awesome.icons.fa_sign_in              ; }
    Awesome.Text { text: "fa_sign_out"              ;  icon: awesome.icons.fa_sign_out             ; }
    Awesome.Text { text: "fa_signal"                ;  icon: awesome.icons.fa_signal               ; }
    Awesome.Text { text: "fa_sitemap"               ;  icon: awesome.icons.fa_sitemap              ; }
    Awesome.Text { text: "fa_skype"                 ;  icon: awesome.icons.fa_skype                ; }
    Awesome.Text { text: "fa_slack"                 ;  icon: awesome.icons.fa_slack                ; }
    Awesome.Text { text: "fa_sliders"               ;  icon: awesome.icons.fa_sliders              ; }
    Awesome.Text { text: "fa_smile_o"               ;  icon: awesome.icons.fa_smile_o              ; }
    Awesome.Text { text: "fa_sort"                  ;  icon: awesome.icons.fa_sort                 ; }
    Awesome.Text { text: "fa_sort_alpha_asc"        ;  icon: awesome.icons.fa_sort_alpha_asc       ; }
    Awesome.Text { text: "fa_sort_alpha_desc"       ;  icon: awesome.icons.fa_sort_alpha_desc      ; }
    Awesome.Text { text: "fa_sort_amount_asc"       ;  icon: awesome.icons.fa_sort_amount_asc      ; }
    Awesome.Text { text: "fa_sort_amount_desc"      ;  icon: awesome.icons.fa_sort_amount_desc     ; }
    Awesome.Text { text: "fa_sort_asc"              ;  icon: awesome.icons.fa_sort_asc             ; }
    Awesome.Text { text: "fa_sort_desc"             ;  icon: awesome.icons.fa_sort_desc            ; }
    Awesome.Text { text: "fa_sort_down"             ;  icon: awesome.icons.fa_sort_down            ; }
    Awesome.Text { text: "fa_sort_numeric_asc"      ;  icon: awesome.icons.fa_sort_numeric_asc     ; }
    Awesome.Text { text: "fa_sort_numeric_desc"     ;  icon: awesome.icons.fa_sort_numeric_desc    ; }
    Awesome.Text { text: "fa_sort_up"               ;  icon: awesome.icons.fa_sort_up              ; }
    Awesome.Text { text: "fa_soundcloud"            ;  icon: awesome.icons.fa_soundcloud           ; }
    Awesome.Text { text: "fa_space_shuttle"         ;  icon: awesome.icons.fa_space_shuttle        ; }
    Awesome.Text { text: "fa_spinner"               ;  icon: awesome.icons.fa_spinner              ; }
    Awesome.Text { text: "fa_spoon"                 ;  icon: awesome.icons.fa_spoon                ; }
    Awesome.Text { text: "fa_spotify"               ;  icon: awesome.icons.fa_spotify              ; }
    Awesome.Text { text: "fa_square"                ;  icon: awesome.icons.fa_square               ; }
    Awesome.Text { text: "fa_square_o"              ;  icon: awesome.icons.fa_square_o             ; }
    Awesome.Text { text: "fa_stack_exchange"        ;  icon: awesome.icons.fa_stack_exchange       ; }
    Awesome.Text { text: "fa_stack_overflow"        ;  icon: awesome.icons.fa_stack_overflow       ; }
    Awesome.Text { text: "fa_star"                  ;  icon: awesome.icons.fa_star                 ; }
    Awesome.Text { text: "fa_star_half"             ;  icon: awesome.icons.fa_star_half            ; }
    Awesome.Text { text: "fa_star_half_empty"       ;  icon: awesome.icons.fa_star_half_empty      ; }
    Awesome.Text { text: "fa_star_half_full"        ;  icon: awesome.icons.fa_star_half_full       ; }
    Awesome.Text { text: "fa_star_half_o"           ;  icon: awesome.icons.fa_star_half_o          ; }
    Awesome.Text { text: "fa_star_o"                ;  icon: awesome.icons.fa_star_o               ; }
    Awesome.Text { text: "fa_steam"                 ;  icon: awesome.icons.fa_steam                ; }
    Awesome.Text { text: "fa_steam_square"          ;  icon: awesome.icons.fa_steam_square         ; }
    Awesome.Text { text: "fa_step_backward"         ;  icon: awesome.icons.fa_step_backward        ; }
    Awesome.Text { text: "fa_step_forward"          ;  icon: awesome.icons.fa_step_forward         ; }
    Awesome.Text { text: "fa_stethoscope"           ;  icon: awesome.icons.fa_stethoscope          ; }
    Awesome.Text { text: "fa_stop"                  ;  icon: awesome.icons.fa_stop                 ; }
    Awesome.Text { text: "fa_strikethrough"         ;  icon: awesome.icons.fa_strikethrough        ; }
    Awesome.Text { text: "fa_stumbleupon"           ;  icon: awesome.icons.fa_stumbleupon          ; }
    Awesome.Text { text: "fa_stumbleupon_circle"    ;  icon: awesome.icons.fa_stumbleupon_circle   ; }
    Awesome.Text { text: "fa_subscript"             ;  icon: awesome.icons.fa_subscript            ; }
    Awesome.Text { text: "fa_suitcase"              ;  icon: awesome.icons.fa_suitcase             ; }
    Awesome.Text { text: "fa_sun_o"                 ;  icon: awesome.icons.fa_sun_o                ; }
    Awesome.Text { text: "fa_superscript"           ;  icon: awesome.icons.fa_superscript          ; }
    Awesome.Text { text: "fa_support"               ;  icon: awesome.icons.fa_support              ; }
    Awesome.Text { text: "fa_table"                 ;  icon: awesome.icons.fa_table                ; }
    Awesome.Text { text: "fa_tablet"                ;  icon: awesome.icons.fa_tablet               ; }
    Awesome.Text { text: "fa_tachometer"            ;  icon: awesome.icons.fa_tachometer           ; }
    Awesome.Text { text: "fa_tag"                   ;  icon: awesome.icons.fa_tag                  ; }
    Awesome.Text { text: "fa_tags"                  ;  icon: awesome.icons.fa_tags                 ; }
    Awesome.Text { text: "fa_tasks"                 ;  icon: awesome.icons.fa_tasks                ; }
    Awesome.Text { text: "fa_taxi"                  ;  icon: awesome.icons.fa_taxi                 ; }
    Awesome.Text { text: "fa_tencent_weibo"         ;  icon: awesome.icons.fa_tencent_weibo        ; }
    Awesome.Text { text: "fa_terminal"              ;  icon: awesome.icons.fa_terminal             ; }
    Awesome.Text { text: "fa_text_height"           ;  icon: awesome.icons.fa_text_height          ; }
    Awesome.Text { text: "fa_text_width"            ;  icon: awesome.icons.fa_text_width           ; }
    Awesome.Text { text: "fa_th"                    ;  icon: awesome.icons.fa_th                   ; }
    Awesome.Text { text: "fa_th_large"              ;  icon: awesome.icons.fa_th_large             ; }
    Awesome.Text { text: "fa_th_list"               ;  icon: awesome.icons.fa_th_list              ; }
    Awesome.Text { text: "fa_thumb_tack"            ;  icon: awesome.icons.fa_thumb_tack           ; }
    Awesome.Text { text: "fa_thumbs_down"           ;  icon: awesome.icons.fa_thumbs_down          ; }
    Awesome.Text { text: "fa_thumbs_o_down"         ;  icon: awesome.icons.fa_thumbs_o_down        ; }
    Awesome.Text { text: "fa_thumbs_o_up"           ;  icon: awesome.icons.fa_thumbs_o_up          ; }
    Awesome.Text { text: "fa_thumbs_up"             ;  icon: awesome.icons.fa_thumbs_up            ; }
    Awesome.Text { text: "fa_ticket"                ;  icon: awesome.icons.fa_ticket               ; }
    Awesome.Text { text: "fa_times"                 ;  icon: awesome.icons.fa_times                ; }
    Awesome.Text { text: "fa_times_circle"          ;  icon: awesome.icons.fa_times_circle         ; }
    Awesome.Text { text: "fa_times_circle_o"        ;  icon: awesome.icons.fa_times_circle_o       ; }
    Awesome.Text { text: "fa_tint"                  ;  icon: awesome.icons.fa_tint                 ; }
    Awesome.Text { text: "fa_toggle_down"           ;  icon: awesome.icons.fa_toggle_down          ; }
    Awesome.Text { text: "fa_toggle_left"           ;  icon: awesome.icons.fa_toggle_left          ; }
    Awesome.Text { text: "fa_toggle_right"          ;  icon: awesome.icons.fa_toggle_right         ; }
    Awesome.Text { text: "fa_toggle_up"             ;  icon: awesome.icons.fa_toggle_up            ; }
    Awesome.Text { text: "fa_trash_o"               ;  icon: awesome.icons.fa_trash_o              ; }
    Awesome.Text { text: "fa_tree"                  ;  icon: awesome.icons.fa_tree                 ; }
    Awesome.Text { text: "fa_trello"                ;  icon: awesome.icons.fa_trello               ; }
    Awesome.Text { text: "fa_trophy"                ;  icon: awesome.icons.fa_trophy               ; }
    Awesome.Text { text: "fa_truck"                 ;  icon: awesome.icons.fa_truck                ; }
    Awesome.Text { text: "fa_try"                   ;  icon: awesome.icons.fa_try                  ; }
    Awesome.Text { text: "fa_tumblr"                ;  icon: awesome.icons.fa_tumblr               ; }
    Awesome.Text { text: "fa_tumblr_square"         ;  icon: awesome.icons.fa_tumblr_square        ; }
    Awesome.Text { text: "fa_turkish_lira"          ;  icon: awesome.icons.fa_turkish_lira         ; }
    Awesome.Text { text: "fa_twitter"               ;  icon: awesome.icons.fa_twitter              ; }
    Awesome.Text { text: "fa_twitter_square"        ;  icon: awesome.icons.fa_twitter_square       ; }
    Awesome.Text { text: "fa_umbrella"              ;  icon: awesome.icons.fa_umbrella             ; }
    Awesome.Text { text: "fa_underline"             ;  icon: awesome.icons.fa_underline            ; }
    Awesome.Text { text: "fa_undo"                  ;  icon: awesome.icons.fa_undo                 ; }
    Awesome.Text { text: "fa_university"            ;  icon: awesome.icons.fa_university           ; }
    Awesome.Text { text: "fa_unlink"                ;  icon: awesome.icons.fa_unlink               ; }
    Awesome.Text { text: "fa_unlock"                ;  icon: awesome.icons.fa_unlock               ; }
    Awesome.Text { text: "fa_unlock_alt"            ;  icon: awesome.icons.fa_unlock_alt           ; }
    Awesome.Text { text: "fa_unsorted"              ;  icon: awesome.icons.fa_unsorted             ; }
    Awesome.Text { text: "fa_upload"                ;  icon: awesome.icons.fa_upload               ; }
    Awesome.Text { text: "fa_usd"                   ;  icon: awesome.icons.fa_usd                  ; }
    Awesome.Text { text: "fa_user"                  ;  icon: awesome.icons.fa_user                 ; }
    Awesome.Text { text: "fa_user_md"               ;  icon: awesome.icons.fa_user_md              ; }
    Awesome.Text { text: "fa_users"                 ;  icon: awesome.icons.fa_users                ; }
    Awesome.Text { text: "fa_video_camera"          ;  icon: awesome.icons.fa_video_camera         ; }
    Awesome.Text { text: "fa_vimeo_square"          ;  icon: awesome.icons.fa_vimeo_square         ; }
    Awesome.Text { text: "fa_vine"                  ;  icon: awesome.icons.fa_vine                 ; }
    Awesome.Text { text: "fa_vk"                    ;  icon: awesome.icons.fa_vk                   ; }
    Awesome.Text { text: "fa_volume_down"           ;  icon: awesome.icons.fa_volume_down          ; }
    Awesome.Text { text: "fa_volume_off"            ;  icon: awesome.icons.fa_volume_off           ; }
    Awesome.Text { text: "fa_volume_up"             ;  icon: awesome.icons.fa_volume_up            ; }
    Awesome.Text { text: "fa_warning"               ;  icon: awesome.icons.fa_warning              ; }
    Awesome.Text { text: "fa_wechat"                ;  icon: awesome.icons.fa_wechat               ; }
    Awesome.Text { text: "fa_weibo"                 ;  icon: awesome.icons.fa_weibo                ; }
    Awesome.Text { text: "fa_weixin"                ;  icon: awesome.icons.fa_weixin               ; }
    Awesome.Text { text: "fa_wheelchair"            ;  icon: awesome.icons.fa_wheelchair           ; }
    Awesome.Text { text: "fa_windows"               ;  icon: awesome.icons.fa_windows              ; }
    Awesome.Text { text: "fa_won"                   ;  icon: awesome.icons.fa_won                  ; }
    Awesome.Text { text: "fa_wordpress"             ;  icon: awesome.icons.fa_wordpress            ; }
    Awesome.Text { text: "fa_wrench"                ;  icon: awesome.icons.fa_wrench               ; }
    Awesome.Text { text: "fa_xing"                  ;  icon: awesome.icons.fa_xing                 ; }
    Awesome.Text { text: "fa_xing_square"           ;  icon: awesome.icons.fa_xing_square          ; }
    Awesome.Text { text: "fa_yahoo"                 ;  icon: awesome.icons.fa_yahoo                ; }
    Awesome.Text { text: "fa_yen"                   ;  icon: awesome.icons.fa_yen                  ; }
    Awesome.Text { text: "fa_youtube"               ;  icon: awesome.icons.fa_youtube              ; }
    Awesome.Text { text: "fa_youtube_play"          ;  icon: awesome.icons.fa_youtube_play         ; }
    Awesome.Text { text: "fa_youtube_square"        ;  icon: awesome.icons.fa_youtube_square       ; }
}
