
/****************************************************************************
**
** The MIT License (MIT)
**
** Copyright (c) 2014 Ricardo do Valle Flores de Oliveira
**
** Permission is hereby granted, free of charge, to any person obtaining a copy
** of this software and associated documentation files (the "Software"), to deal
** in the Software without restriction, including without limitation the rights
** to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
** copies of the Software, and to permit persons to whom the Software is
** furnished to do so, subject to the following conditions:
**
** The above copyright notice and this permission notice shall be included in
** all copies or substantial portions of the Software.
**
** THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
** IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
** FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
** AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
** LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
** OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
** SOFTWARE.
**
**
****************************************************************************/

import QtQuick 2.0

ListModel {
    ListElement { name: "fa_adjust"                ;  character: "\uf042" ; }
    ListElement { name: "fa_adn"                   ;  character: "\uf170" ; }
    ListElement { name: "fa_align_center"          ;  character: "\uf037" ; }
    ListElement { name: "fa_align_justify"         ;  character: "\uf039" ; }
    ListElement { name: "fa_align_left"            ;  character: "\uf036" ; }
    ListElement { name: "fa_align_right"           ;  character: "\uf038" ; }
    ListElement { name: "fa_ambulance"             ;  character: "\uf0f9" ; }
    ListElement { name: "fa_anchor"                ;  character: "\uf13d" ; }
    ListElement { name: "fa_android"               ;  character: "\uf17b" ; }
    ListElement { name: "fa_angle_double_down"     ;  character: "\uf103" ; }
    ListElement { name: "fa_angle_double_left"     ;  character: "\uf100" ; }
    ListElement { name: "fa_angle_double_right"    ;  character: "\uf101" ; }
    ListElement { name: "fa_angle_double_up"       ;  character: "\uf102" ; }
    ListElement { name: "fa_angle_down"            ;  character: "\uf107" ; }
    ListElement { name: "fa_angle_left"            ;  character: "\uf104" ; }
    ListElement { name: "fa_angle_right"           ;  character: "\uf105" ; }
    ListElement { name: "fa_angle_up"              ;  character: "\uf106" ; }
    ListElement { name: "fa_apple"                 ;  character: "\uf179" ; }
    ListElement { name: "fa_archive"               ;  character: "\uf187" ; }
    ListElement { name: "fa_arrow_circle_down"     ;  character: "\uf0ab" ; }
    ListElement { name: "fa_arrow_circle_left"     ;  character: "\uf0a8" ; }
    ListElement { name: "fa_arrow_circle_o_down"   ;  character: "\uf01a" ; }
    ListElement { name: "fa_arrow_circle_o_left"   ;  character: "\uf190" ; }
    ListElement { name: "fa_arrow_circle_o_right"  ;  character: "\uf18e" ; }
    ListElement { name: "fa_arrow_circle_o_up"     ;  character: "\uf01b" ; }
    ListElement { name: "fa_arrow_circle_right"    ;  character: "\uf0a9" ; }
    ListElement { name: "fa_arrow_circle_up"       ;  character: "\uf0aa" ; }
    ListElement { name: "fa_arrow_down"            ;  character: "\uf063" ; }
    ListElement { name: "fa_arrow_left"            ;  character: "\uf060" ; }
    ListElement { name: "fa_arrow_right"           ;  character: "\uf061" ; }
    ListElement { name: "fa_arrow_up"              ;  character: "\uf062" ; }
    ListElement { name: "fa_arrows"                ;  character: "\uf047" ; }
    ListElement { name: "fa_arrows_alt"            ;  character: "\uf0b2" ; }
    ListElement { name: "fa_arrows_h"              ;  character: "\uf07e" ; }
    ListElement { name: "fa_arrows_v"              ;  character: "\uf07d" ; }
    ListElement { name: "fa_asterisk"              ;  character: "\uf069" ; }
    ListElement { name: "fa_automobile"            ;  character: "\uf1b9" ; }
    ListElement { name: "fa_backward"              ;  character: "\uf04a" ; }
    ListElement { name: "fa_ban"                   ;  character: "\uf05e" ; }
    ListElement { name: "fa_bank"                  ;  character: "\uf19c" ; }
    ListElement { name: "fa_bar_chart_o"           ;  character: "\uf080" ; }
    ListElement { name: "fa_barcode"               ;  character: "\uf02a" ; }
    ListElement { name: "fa_bars"                  ;  character: "\uf0c9" ; }
    ListElement { name: "fa_beer"                  ;  character: "\uf0fc" ; }
    ListElement { name: "fa_behance"               ;  character: "\uf1b4" ; }
    ListElement { name: "fa_behance_square"        ;  character: "\uf1b5" ; }
    ListElement { name: "fa_bell"                  ;  character: "\uf0f3" ; }
    ListElement { name: "fa_bell_o"                ;  character: "\uf0a2" ; }
    ListElement { name: "fa_bitbucket"             ;  character: "\uf171" ; }
    ListElement { name: "fa_bitbucket_square"      ;  character: "\uf172" ; }
    ListElement { name: "fa_bitcoin"               ;  character: "\uf15a" ; }
    ListElement { name: "fa_bold"                  ;  character: "\uf032" ; }
    ListElement { name: "fa_bolt"                  ;  character: "\uf0e7" ; }
    ListElement { name: "fa_bomb"                  ;  character: "\uf1e2" ; }
    ListElement { name: "fa_book"                  ;  character: "\uf02d" ; }
    ListElement { name: "fa_bookmark"              ;  character: "\uf02e" ; }
    ListElement { name: "fa_bookmark_o"            ;  character: "\uf097" ; }
    ListElement { name: "fa_briefcase"             ;  character: "\uf0b1" ; }
    ListElement { name: "fa_btc"                   ;  character: "\uf15a" ; }
    ListElement { name: "fa_bug"                   ;  character: "\uf188" ; }
    ListElement { name: "fa_building"              ;  character: "\uf1ad" ; }
    ListElement { name: "fa_building_o"            ;  character: "\uf0f7" ; }
    ListElement { name: "fa_bullhorn"              ;  character: "\uf0a1" ; }
    ListElement { name: "fa_bullseye"              ;  character: "\uf140" ; }
    ListElement { name: "fa_cab"                   ;  character: "\uf1ba" ; }
    ListElement { name: "fa_calendar"              ;  character: "\uf073" ; }
    ListElement { name: "fa_calendar_o"            ;  character: "\uf133" ; }
    ListElement { name: "fa_camera"                ;  character: "\uf030" ; }
    ListElement { name: "fa_camera_retro"          ;  character: "\uf083" ; }
    ListElement { name: "fa_car"                   ;  character: "\uf1b9" ; }
    ListElement { name: "fa_caret_down"            ;  character: "\uf0d7" ; }
    ListElement { name: "fa_caret_left"            ;  character: "\uf0d9" ; }
    ListElement { name: "fa_caret_right"           ;  character: "\uf0da" ; }
    ListElement { name: "fa_caret_square_o_down"   ;  character: "\uf150" ; }
    ListElement { name: "fa_caret_square_o_left"   ;  character: "\uf191" ; }
    ListElement { name: "fa_caret_square_o_right"  ;  character: "\uf152" ; }
    ListElement { name: "fa_caret_square_o_up"     ;  character: "\uf151" ; }
    ListElement { name: "fa_caret_up"              ;  character: "\uf0d8" ; }
    ListElement { name: "fa_certificate"           ;  character: "\uf0a3" ; }
    ListElement { name: "fa_chain"                 ;  character: "\uf0c1" ; }
    ListElement { name: "fa_chain_broken"          ;  character: "\uf127" ; }
    ListElement { name: "fa_check"                 ;  character: "\uf00c" ; }
    ListElement { name: "fa_check_circle"          ;  character: "\uf058" ; }
    ListElement { name: "fa_check_circle_o"        ;  character: "\uf05d" ; }
    ListElement { name: "fa_check_square"          ;  character: "\uf14a" ; }
    ListElement { name: "fa_check_square_o"        ;  character: "\uf046" ; }
    ListElement { name: "fa_chevron_circle_down"   ;  character: "\uf13a" ; }
    ListElement { name: "fa_chevron_circle_left"   ;  character: "\uf137" ; }
    ListElement { name: "fa_chevron_circle_right"  ;  character: "\uf138" ; }
    ListElement { name: "fa_chevron_circle_up"     ;  character: "\uf139" ; }
    ListElement { name: "fa_chevron_down"          ;  character: "\uf078" ; }
    ListElement { name: "fa_chevron_left"          ;  character: "\uf053" ; }
    ListElement { name: "fa_chevron_right"         ;  character: "\uf054" ; }
    ListElement { name: "fa_chevron_up"            ;  character: "\uf077" ; }
    ListElement { name: "fa_child"                 ;  character: "\uf1ae" ; }
    ListElement { name: "fa_circle"                ;  character: "\uf111" ; }
    ListElement { name: "fa_circle_o"              ;  character: "\uf10c" ; }
    ListElement { name: "fa_circle_o_notch"        ;  character: "\uf1ce" ; }
    ListElement { name: "fa_circle_thin"           ;  character: "\uf1db" ; }
    ListElement { name: "fa_clipboard"             ;  character: "\uf0ea" ; }
    ListElement { name: "fa_clock_o"               ;  character: "\uf017" ; }
    ListElement { name: "fa_cloud"                 ;  character: "\uf0c2" ; }
    ListElement { name: "fa_cloud_download"        ;  character: "\uf0ed" ; }
    ListElement { name: "fa_cloud_upload"          ;  character: "\uf0ee" ; }
    ListElement { name: "fa_cny"                   ;  character: "\uf157" ; }
    ListElement { name: "fa_code"                  ;  character: "\uf121" ; }
    ListElement { name: "fa_code_fork"             ;  character: "\uf126" ; }
    ListElement { name: "fa_codepen"               ;  character: "\uf1cb" ; }
    ListElement { name: "fa_coffee"                ;  character: "\uf0f4" ; }
    ListElement { name: "fa_cog"                   ;  character: "\uf013" ; }
    ListElement { name: "fa_cogs"                  ;  character: "\uf085" ; }
    ListElement { name: "fa_columns"               ;  character: "\uf0db" ; }
    ListElement { name: "fa_comment"               ;  character: "\uf075" ; }
    ListElement { name: "fa_comment_o"             ;  character: "\uf0e5" ; }
    ListElement { name: "fa_comments"              ;  character: "\uf086" ; }
    ListElement { name: "fa_comments_o"            ;  character: "\uf0e6" ; }
    ListElement { name: "fa_compass"               ;  character: "\uf14e" ; }
    ListElement { name: "fa_compress"              ;  character: "\uf066" ; }
    ListElement { name: "fa_copy"                  ;  character: "\uf0c5" ; }
    ListElement { name: "fa_credit_card"           ;  character: "\uf09d" ; }
    ListElement { name: "fa_crop"                  ;  character: "\uf125" ; }
    ListElement { name: "fa_crosshairs"            ;  character: "\uf05b" ; }
    ListElement { name: "fa_css3"                  ;  character: "\uf13c" ; }
    ListElement { name: "fa_cube"                  ;  character: "\uf1b2" ; }
    ListElement { name: "fa_cubes"                 ;  character: "\uf1b3" ; }
    ListElement { name: "fa_cut"                   ;  character: "\uf0c4" ; }
    ListElement { name: "fa_cutlery"               ;  character: "\uf0f5" ; }
    ListElement { name: "fa_dashboard"             ;  character: "\uf0e4" ; }
    ListElement { name: "fa_database"              ;  character: "\uf1c0" ; }
    ListElement { name: "fa_dedent"                ;  character: "\uf03b" ; }
    ListElement { name: "fa_delicious"             ;  character: "\uf1a5" ; }
    ListElement { name: "fa_desktop"               ;  character: "\uf108" ; }
    ListElement { name: "fa_deviantart"            ;  character: "\uf1bd" ; }
    ListElement { name: "fa_digg"                  ;  character: "\uf1a6" ; }
    ListElement { name: "fa_dollar"                ;  character: "\uf155" ; }
    ListElement { name: "fa_dot_circle_o"          ;  character: "\uf192" ; }
    ListElement { name: "fa_download"              ;  character: "\uf019" ; }
    ListElement { name: "fa_dribbble"              ;  character: "\uf17d" ; }
    ListElement { name: "fa_dropbox"               ;  character: "\uf16b" ; }
    ListElement { name: "fa_drupal"                ;  character: "\uf1a9" ; }
    ListElement { name: "fa_edit"                  ;  character: "\uf044" ; }
    ListElement { name: "fa_eject"                 ;  character: "\uf052" ; }
    ListElement { name: "fa_ellipsis_h"            ;  character: "\uf141" ; }
    ListElement { name: "fa_ellipsis_v"            ;  character: "\uf142" ; }
    ListElement { name: "fa_empire"                ;  character: "\uf1d1" ; }
    ListElement { name: "fa_envelope"              ;  character: "\uf0e0" ; }
    ListElement { name: "fa_envelope_o"            ;  character: "\uf003" ; }
    ListElement { name: "fa_envelope_square"       ;  character: "\uf199" ; }
    ListElement { name: "fa_eraser"                ;  character: "\uf12d" ; }
    ListElement { name: "fa_eur"                   ;  character: "\uf153" ; }
    ListElement { name: "fa_euro"                  ;  character: "\uf153" ; }
    ListElement { name: "fa_exchange"              ;  character: "\uf0ec" ; }
    ListElement { name: "fa_exclamation"           ;  character: "\uf12a" ; }
    ListElement { name: "fa_exclamation_circle"    ;  character: "\uf06a" ; }
    ListElement { name: "fa_exclamation_triangle"  ;  character: "\uf071" ; }
    ListElement { name: "fa_expand"                ;  character: "\uf065" ; }
    ListElement { name: "fa_external_link"         ;  character: "\uf08e" ; }
    ListElement { name: "fa_external_link_square"  ;  character: "\uf14c" ; }
    ListElement { name: "fa_eye"                   ;  character: "\uf06e" ; }
    ListElement { name: "fa_eye_slash"             ;  character: "\uf070" ; }
    ListElement { name: "fa_facebook"              ;  character: "\uf09a" ; }
    ListElement { name: "fa_facebook_square"       ;  character: "\uf082" ; }
    ListElement { name: "fa_fast_backward"         ;  character: "\uf049" ; }
    ListElement { name: "fa_fast_forward"          ;  character: "\uf050" ; }
    ListElement { name: "fa_fax"                   ;  character: "\uf1ac" ; }
    ListElement { name: "fa_female"                ;  character: "\uf182" ; }
    ListElement { name: "fa_fighter_jet"           ;  character: "\uf0fb" ; }
    ListElement { name: "fa_file"                  ;  character: "\uf15b" ; }
    ListElement { name: "fa_file_archive_o"        ;  character: "\uf1c6" ; }
    ListElement { name: "fa_file_audio_o"          ;  character: "\uf1c7" ; }
    ListElement { name: "fa_file_code_o"           ;  character: "\uf1c9" ; }
    ListElement { name: "fa_file_excel_o"          ;  character: "\uf1c3" ; }
    ListElement { name: "fa_file_image_o"          ;  character: "\uf1c5" ; }
    ListElement { name: "fa_file_movie_o"          ;  character: "\uf1c8" ; }
    ListElement { name: "fa_file_o"                ;  character: "\uf016" ; }
    ListElement { name: "fa_file_pdf_o"            ;  character: "\uf1c1" ; }
    ListElement { name: "fa_file_photo_o"          ;  character: "\uf1c5" ; }
    ListElement { name: "fa_file_picture_o"        ;  character: "\uf1c5" ; }
    ListElement { name: "fa_file_powerpoint_o"     ;  character: "\uf1c4" ; }
    ListElement { name: "fa_file_sound_o"          ;  character: "\uf1c7" ; }
    ListElement { name: "fa_file_text"             ;  character: "\uf15c" ; }
    ListElement { name: "fa_file_text_o"           ;  character: "\uf0f6" ; }
    ListElement { name: "fa_file_video_o"          ;  character: "\uf1c8" ; }
    ListElement { name: "fa_file_word_o"           ;  character: "\uf1c2" ; }
    ListElement { name: "fa_file_zip_o"            ;  character: "\uf1c6" ; }
    ListElement { name: "fa_files_o"               ;  character: "\uf0c5" ; }
    ListElement { name: "fa_film"                  ;  character: "\uf008" ; }
    ListElement { name: "fa_filter"                ;  character: "\uf0b0" ; }
    ListElement { name: "fa_fire"                  ;  character: "\uf06d" ; }
    ListElement { name: "fa_fire_extinguisher"     ;  character: "\uf134" ; }
    ListElement { name: "fa_flag"                  ;  character: "\uf024" ; }
    ListElement { name: "fa_flag_checkered"        ;  character: "\uf11e" ; }
    ListElement { name: "fa_flag_o"                ;  character: "\uf11d" ; }
    ListElement { name: "fa_flash"                 ;  character: "\uf0e7" ; }
    ListElement { name: "fa_flask"                 ;  character: "\uf0c3" ; }
    ListElement { name: "fa_flickr"                ;  character: "\uf16e" ; }
    ListElement { name: "fa_floppy_o"              ;  character: "\uf0c7" ; }
    ListElement { name: "fa_folder"                ;  character: "\uf07b" ; }
    ListElement { name: "fa_folder_o"              ;  character: "\uf114" ; }
    ListElement { name: "fa_folder_open"           ;  character: "\uf07c" ; }
    ListElement { name: "fa_folder_open_o"         ;  character: "\uf115" ; }
    ListElement { name: "fa_font"                  ;  character: "\uf031" ; }
    ListElement { name: "fa_forward"               ;  character: "\uf04e" ; }
    ListElement { name: "fa_foursquare"            ;  character: "\uf180" ; }
    ListElement { name: "fa_frown_o"               ;  character: "\uf119" ; }
    ListElement { name: "fa_gamepad"               ;  character: "\uf11b" ; }
    ListElement { name: "fa_gavel"                 ;  character: "\uf0e3" ; }
    ListElement { name: "fa_gbp"                   ;  character: "\uf154" ; }
    ListElement { name: "fa_ge"                    ;  character: "\uf1d1" ; }
    ListElement { name: "fa_gear"                  ;  character: "\uf013" ; }
    ListElement { name: "fa_gears"                 ;  character: "\uf085" ; }
    ListElement { name: "fa_gift"                  ;  character: "\uf06b" ; }
    ListElement { name: "fa_git"                   ;  character: "\uf1d3" ; }
    ListElement { name: "fa_git_square"            ;  character: "\uf1d2" ; }
    ListElement { name: "fa_github"                ;  character: "\uf09b" ; }
    ListElement { name: "fa_github_alt"            ;  character: "\uf113" ; }
    ListElement { name: "fa_github_square"         ;  character: "\uf092" ; }
    ListElement { name: "fa_gittip"                ;  character: "\uf184" ; }
    ListElement { name: "fa_glass"                 ;  character: "\uf000" ; }
    ListElement { name: "fa_globe"                 ;  character: "\uf0ac" ; }
    ListElement { name: "fa_google"                ;  character: "\uf1a0" ; }
    ListElement { name: "fa_google_plus"           ;  character: "\uf0d5" ; }
    ListElement { name: "fa_google_plus_square"    ;  character: "\uf0d4" ; }
    ListElement { name: "fa_graduation_cap"        ;  character: "\uf19d" ; }
    ListElement { name: "fa_group"                 ;  character: "\uf0c0" ; }
    ListElement { name: "fa_h_square"              ;  character: "\uf0fd" ; }
    ListElement { name: "fa_hacker_news"           ;  character: "\uf1d4" ; }
    ListElement { name: "fa_hand_o_down"           ;  character: "\uf0a7" ; }
    ListElement { name: "fa_hand_o_left"           ;  character: "\uf0a5" ; }
    ListElement { name: "fa_hand_o_right"          ;  character: "\uf0a4" ; }
    ListElement { name: "fa_hand_o_up"             ;  character: "\uf0a6" ; }
    ListElement { name: "fa_hdd_o"                 ;  character: "\uf0a0" ; }
    ListElement { name: "fa_header"                ;  character: "\uf1dc" ; }
    ListElement { name: "fa_headphones"            ;  character: "\uf025" ; }
    ListElement { name: "fa_heart"                 ;  character: "\uf004" ; }
    ListElement { name: "fa_heart_o"               ;  character: "\uf08a" ; }
    ListElement { name: "fa_history"               ;  character: "\uf1da" ; }
    ListElement { name: "fa_home"                  ;  character: "\uf015" ; }
    ListElement { name: "fa_hospital_o"            ;  character: "\uf0f8" ; }
    ListElement { name: "fa_html5"                 ;  character: "\uf13b" ; }
    ListElement { name: "fa_image"                 ;  character: "\uf03e" ; }
    ListElement { name: "fa_inbox"                 ;  character: "\uf01c" ; }
    ListElement { name: "fa_indent"                ;  character: "\uf03c" ; }
    ListElement { name: "fa_info"                  ;  character: "\uf129" ; }
    ListElement { name: "fa_info_circle"           ;  character: "\uf05a" ; }
    ListElement { name: "fa_inr"                   ;  character: "\uf156" ; }
    ListElement { name: "fa_instagram"             ;  character: "\uf16d" ; }
    ListElement { name: "fa_institution"           ;  character: "\uf19c" ; }
    ListElement { name: "fa_italic"                ;  character: "\uf033" ; }
    ListElement { name: "fa_joomla"                ;  character: "\uf1aa" ; }
    ListElement { name: "fa_jpy"                   ;  character: "\uf157" ; }
    ListElement { name: "fa_jsfiddle"              ;  character: "\uf1cc" ; }
    ListElement { name: "fa_key"                   ;  character: "\uf084" ; }
    ListElement { name: "fa_keyboard_o"            ;  character: "\uf11c" ; }
    ListElement { name: "fa_krw"                   ;  character: "\uf159" ; }
    ListElement { name: "fa_language"              ;  character: "\uf1ab" ; }
    ListElement { name: "fa_laptop"                ;  character: "\uf109" ; }
    ListElement { name: "fa_leaf"                  ;  character: "\uf06c" ; }
    ListElement { name: "fa_legal"                 ;  character: "\uf0e3" ; }
    ListElement { name: "fa_lemon_o"               ;  character: "\uf094" ; }
    ListElement { name: "fa_level_down"            ;  character: "\uf149" ; }
    ListElement { name: "fa_level_up"              ;  character: "\uf148" ; }
    ListElement { name: "fa_life_bouy"             ;  character: "\uf1cd" ; }
    ListElement { name: "fa_life_ring"             ;  character: "\uf1cd" ; }
    ListElement { name: "fa_life_saver"            ;  character: "\uf1cd" ; }
    ListElement { name: "fa_lightbulb_o"           ;  character: "\uf0eb" ; }
    ListElement { name: "fa_link"                  ;  character: "\uf0c1" ; }
    ListElement { name: "fa_linkedin"              ;  character: "\uf0e1" ; }
    ListElement { name: "fa_linkedin_square"       ;  character: "\uf08c" ; }
    ListElement { name: "fa_linux"                 ;  character: "\uf17c" ; }
    ListElement { name: "fa_list"                  ;  character: "\uf03a" ; }
    ListElement { name: "fa_list_alt"              ;  character: "\uf022" ; }
    ListElement { name: "fa_list_ol"               ;  character: "\uf0cb" ; }
    ListElement { name: "fa_list_ul"               ;  character: "\uf0ca" ; }
    ListElement { name: "fa_location_arrow"        ;  character: "\uf124" ; }
    ListElement { name: "fa_lock"                  ;  character: "\uf023" ; }
    ListElement { name: "fa_long_arrow_down"       ;  character: "\uf175" ; }
    ListElement { name: "fa_long_arrow_left"       ;  character: "\uf177" ; }
    ListElement { name: "fa_long_arrow_right"      ;  character: "\uf178" ; }
    ListElement { name: "fa_long_arrow_up"         ;  character: "\uf176" ; }
    ListElement { name: "fa_magic"                 ;  character: "\uf0d0" ; }
    ListElement { name: "fa_magnet"                ;  character: "\uf076" ; }
    ListElement { name: "fa_mail_forward"          ;  character: "\uf064" ; }
    ListElement { name: "fa_mail_reply"            ;  character: "\uf112" ; }
    ListElement { name: "fa_mail_reply_all"        ;  character: "\uf122" ; }
    ListElement { name: "fa_male"                  ;  character: "\uf183" ; }
    ListElement { name: "fa_map_marker"            ;  character: "\uf041" ; }
    ListElement { name: "fa_maxcdn"                ;  character: "\uf136" ; }
    ListElement { name: "fa_medkit"                ;  character: "\uf0fa" ; }
    ListElement { name: "fa_meh_o"                 ;  character: "\uf11a" ; }
    ListElement { name: "fa_microphone"            ;  character: "\uf130" ; }
    ListElement { name: "fa_microphone_slash"      ;  character: "\uf131" ; }
    ListElement { name: "fa_minus"                 ;  character: "\uf068" ; }
    ListElement { name: "fa_minus_circle"          ;  character: "\uf056" ; }
    ListElement { name: "fa_minus_square"          ;  character: "\uf146" ; }
    ListElement { name: "fa_minus_square_o"        ;  character: "\uf147" ; }
    ListElement { name: "fa_mobile"                ;  character: "\uf10b" ; }
    ListElement { name: "fa_mobile_phone"          ;  character: "\uf10b" ; }
    ListElement { name: "fa_money"                 ;  character: "\uf0d6" ; }
    ListElement { name: "fa_moon_o"                ;  character: "\uf186" ; }
    ListElement { name: "fa_mortar_board"          ;  character: "\uf19d" ; }
    ListElement { name: "fa_music"                 ;  character: "\uf001" ; }
    ListElement { name: "fa_navicon"               ;  character: "\uf0c9" ; }
    ListElement { name: "fa_openid"                ;  character: "\uf19b" ; }
    ListElement { name: "fa_outdent"               ;  character: "\uf03b" ; }
    ListElement { name: "fa_pagelines"             ;  character: "\uf18c" ; }
    ListElement { name: "fa_paper_plane"           ;  character: "\uf1d8" ; }
    ListElement { name: "fa_paper_plane_o"         ;  character: "\uf1d9" ; }
    ListElement { name: "fa_paperclip"             ;  character: "\uf0c6" ; }
    ListElement { name: "fa_paragraph"             ;  character: "\uf1dd" ; }
    ListElement { name: "fa_paste"                 ;  character: "\uf0ea" ; }
    ListElement { name: "fa_pause"                 ;  character: "\uf04c" ; }
    ListElement { name: "fa_paw"                   ;  character: "\uf1b0" ; }
    ListElement { name: "fa_pencil"                ;  character: "\uf040" ; }
    ListElement { name: "fa_pencil_square"         ;  character: "\uf14b" ; }
    ListElement { name: "fa_pencil_square_o"       ;  character: "\uf044" ; }
    ListElement { name: "fa_phone"                 ;  character: "\uf095" ; }
    ListElement { name: "fa_phone_square"          ;  character: "\uf098" ; }
    ListElement { name: "fa_photo"                 ;  character: "\uf03e" ; }
    ListElement { name: "fa_picture_o"             ;  character: "\uf03e" ; }
    ListElement { name: "fa_pied_piper"            ;  character: "\uf1a7" ; }
    ListElement { name: "fa_pied_piper_alt"        ;  character: "\uf1a8" ; }
    ListElement { name: "fa_pied_piper_square"     ;  character: "\uf1a7" ; }
    ListElement { name: "fa_pinterest"             ;  character: "\uf0d2" ; }
    ListElement { name: "fa_pinterest_square"      ;  character: "\uf0d3" ; }
    ListElement { name: "fa_plane"                 ;  character: "\uf072" ; }
    ListElement { name: "fa_play"                  ;  character: "\uf04b" ; }
    ListElement { name: "fa_play_circle"           ;  character: "\uf144" ; }
    ListElement { name: "fa_play_circle_o"         ;  character: "\uf01d" ; }
    ListElement { name: "fa_plus"                  ;  character: "\uf067" ; }
    ListElement { name: "fa_plus_circle"           ;  character: "\uf055" ; }
    ListElement { name: "fa_plus_square"           ;  character: "\uf0fe" ; }
    ListElement { name: "fa_plus_square_o"         ;  character: "\uf196" ; }
    ListElement { name: "fa_power_off"             ;  character: "\uf011" ; }
    ListElement { name: "fa_print"                 ;  character: "\uf02f" ; }
    ListElement { name: "fa_puzzle_piece"          ;  character: "\uf12e" ; }
    ListElement { name: "fa_qq"                    ;  character: "\uf1d6" ; }
    ListElement { name: "fa_qrcode"                ;  character: "\uf029" ; }
    ListElement { name: "fa_question"              ;  character: "\uf128" ; }
    ListElement { name: "fa_question_circle"       ;  character: "\uf059" ; }
    ListElement { name: "fa_quote_left"            ;  character: "\uf10d" ; }
    ListElement { name: "fa_quote_right"           ;  character: "\uf10e" ; }
    ListElement { name: "fa_ra"                    ;  character: "\uf1d0" ; }
    ListElement { name: "fa_random"                ;  character: "\uf074" ; }
    ListElement { name: "fa_rebel"                 ;  character: "\uf1d0" ; }
    ListElement { name: "fa_recycle"               ;  character: "\uf1b8" ; }
    ListElement { name: "fa_reddit"                ;  character: "\uf1a1" ; }
    ListElement { name: "fa_reddit_square"         ;  character: "\uf1a2" ; }
    ListElement { name: "fa_refresh"               ;  character: "\uf021" ; }
    ListElement { name: "fa_renren"                ;  character: "\uf18b" ; }
    ListElement { name: "fa_reorder"               ;  character: "\uf0c9" ; }
    ListElement { name: "fa_repeat"                ;  character: "\uf01e" ; }
    ListElement { name: "fa_reply"                 ;  character: "\uf112" ; }
    ListElement { name: "fa_reply_all"             ;  character: "\uf122" ; }
    ListElement { name: "fa_retweet"               ;  character: "\uf079" ; }
    ListElement { name: "fa_rmb"                   ;  character: "\uf157" ; }
    ListElement { name: "fa_road"                  ;  character: "\uf018" ; }
    ListElement { name: "fa_rocket"                ;  character: "\uf135" ; }
    ListElement { name: "fa_rotate_left"           ;  character: "\uf0e2" ; }
    ListElement { name: "fa_rotate_right"          ;  character: "\uf01e" ; }
    ListElement { name: "fa_rouble"                ;  character: "\uf158" ; }
    ListElement { name: "fa_rss"                   ;  character: "\uf09e" ; }
    ListElement { name: "fa_rss_square"            ;  character: "\uf143" ; }
    ListElement { name: "fa_rub"                   ;  character: "\uf158" ; }
    ListElement { name: "fa_ruble"                 ;  character: "\uf158" ; }
    ListElement { name: "fa_rupee"                 ;  character: "\uf156" ; }
    ListElement { name: "fa_save"                  ;  character: "\uf0c7" ; }
    ListElement { name: "fa_scissors"              ;  character: "\uf0c4" ; }
    ListElement { name: "fa_search"                ;  character: "\uf002" ; }
    ListElement { name: "fa_search_minus"          ;  character: "\uf010" ; }
    ListElement { name: "fa_search_plus"           ;  character: "\uf00e" ; }
    ListElement { name: "fa_send"                  ;  character: "\uf1d8" ; }
    ListElement { name: "fa_send_o"                ;  character: "\uf1d9" ; }
    ListElement { name: "fa_share"                 ;  character: "\uf064" ; }
    ListElement { name: "fa_share_alt"             ;  character: "\uf1e0" ; }
    ListElement { name: "fa_share_alt_square"      ;  character: "\uf1e1" ; }
    ListElement { name: "fa_share_square"          ;  character: "\uf14d" ; }
    ListElement { name: "fa_share_square_o"        ;  character: "\uf045" ; }
    ListElement { name: "fa_shield"                ;  character: "\uf132" ; }
    ListElement { name: "fa_shopping_cart"         ;  character: "\uf07a" ; }
    ListElement { name: "fa_sign_in"               ;  character: "\uf090" ; }
    ListElement { name: "fa_sign_out"              ;  character: "\uf08b" ; }
    ListElement { name: "fa_signal"                ;  character: "\uf012" ; }
    ListElement { name: "fa_sitemap"               ;  character: "\uf0e8" ; }
    ListElement { name: "fa_skype"                 ;  character: "\uf17e" ; }
    ListElement { name: "fa_slack"                 ;  character: "\uf198" ; }
    ListElement { name: "fa_sliders"               ;  character: "\uf1de" ; }
    ListElement { name: "fa_smile_o"               ;  character: "\uf118" ; }
    ListElement { name: "fa_sort"                  ;  character: "\uf0dc" ; }
    ListElement { name: "fa_sort_alpha_asc"        ;  character: "\uf15d" ; }
    ListElement { name: "fa_sort_alpha_desc"       ;  character: "\uf15e" ; }
    ListElement { name: "fa_sort_amount_asc"       ;  character: "\uf160" ; }
    ListElement { name: "fa_sort_amount_desc"      ;  character: "\uf161" ; }
    ListElement { name: "fa_sort_asc"              ;  character: "\uf0de" ; }
    ListElement { name: "fa_sort_desc"             ;  character: "\uf0dd" ; }
    ListElement { name: "fa_sort_down"             ;  character: "\uf0dd" ; }
    ListElement { name: "fa_sort_numeric_asc"      ;  character: "\uf162" ; }
    ListElement { name: "fa_sort_numeric_desc"     ;  character: "\uf163" ; }
    ListElement { name: "fa_sort_up"               ;  character: "\uf0de" ; }
    ListElement { name: "fa_soundcloud"            ;  character: "\uf1be" ; }
    ListElement { name: "fa_space_shuttle"         ;  character: "\uf197" ; }
    ListElement { name: "fa_spinner"               ;  character: "\uf110" ; }
    ListElement { name: "fa_spoon"                 ;  character: "\uf1b1" ; }
    ListElement { name: "fa_spotify"               ;  character: "\uf1bc" ; }
    ListElement { name: "fa_square"                ;  character: "\uf0c8" ; }
    ListElement { name: "fa_square_o"              ;  character: "\uf096" ; }
    ListElement { name: "fa_stack_exchange"        ;  character: "\uf18d" ; }
    ListElement { name: "fa_stack_overflow"        ;  character: "\uf16c" ; }
    ListElement { name: "fa_star"                  ;  character: "\uf005" ; }
    ListElement { name: "fa_star_half"             ;  character: "\uf089" ; }
    ListElement { name: "fa_star_half_empty"       ;  character: "\uf123" ; }
    ListElement { name: "fa_star_half_full"        ;  character: "\uf123" ; }
    ListElement { name: "fa_star_half_o"           ;  character: "\uf123" ; }
    ListElement { name: "fa_star_o"                ;  character: "\uf006" ; }
    ListElement { name: "fa_steam"                 ;  character: "\uf1b6" ; }
    ListElement { name: "fa_steam_square"          ;  character: "\uf1b7" ; }
    ListElement { name: "fa_step_backward"         ;  character: "\uf048" ; }
    ListElement { name: "fa_step_forward"          ;  character: "\uf051" ; }
    ListElement { name: "fa_stethoscope"           ;  character: "\uf0f1" ; }
    ListElement { name: "fa_stop"                  ;  character: "\uf04d" ; }
    ListElement { name: "fa_strikethrough"         ;  character: "\uf0cc" ; }
    ListElement { name: "fa_stumbleupon"           ;  character: "\uf1a4" ; }
    ListElement { name: "fa_stumbleupon_circle"    ;  character: "\uf1a3" ; }
    ListElement { name: "fa_subscript"             ;  character: "\uf12c" ; }
    ListElement { name: "fa_suitcase"              ;  character: "\uf0f2" ; }
    ListElement { name: "fa_sun_o"                 ;  character: "\uf185" ; }
    ListElement { name: "fa_superscript"           ;  character: "\uf12b" ; }
    ListElement { name: "fa_support"               ;  character: "\uf1cd" ; }
    ListElement { name: "fa_table"                 ;  character: "\uf0ce" ; }
    ListElement { name: "fa_tablet"                ;  character: "\uf10a" ; }
    ListElement { name: "fa_tachometer"            ;  character: "\uf0e4" ; }
    ListElement { name: "fa_tag"                   ;  character: "\uf02b" ; }
    ListElement { name: "fa_tags"                  ;  character: "\uf02c" ; }
    ListElement { name: "fa_tasks"                 ;  character: "\uf0ae" ; }
    ListElement { name: "fa_taxi"                  ;  character: "\uf1ba" ; }
    ListElement { name: "fa_tencent_weibo"         ;  character: "\uf1d5" ; }
    ListElement { name: "fa_terminal"              ;  character: "\uf120" ; }
    ListElement { name: "fa_text_height"           ;  character: "\uf034" ; }
    ListElement { name: "fa_text_width"            ;  character: "\uf035" ; }
    ListElement { name: "fa_th"                    ;  character: "\uf00a" ; }
    ListElement { name: "fa_th_large"              ;  character: "\uf009" ; }
    ListElement { name: "fa_th_list"               ;  character: "\uf00b" ; }
    ListElement { name: "fa_thumb_tack"            ;  character: "\uf08d" ; }
    ListElement { name: "fa_thumbs_down"           ;  character: "\uf165" ; }
    ListElement { name: "fa_thumbs_o_down"         ;  character: "\uf088" ; }
    ListElement { name: "fa_thumbs_o_up"           ;  character: "\uf087" ; }
    ListElement { name: "fa_thumbs_up"             ;  character: "\uf164" ; }
    ListElement { name: "fa_ticket"                ;  character: "\uf145" ; }
    ListElement { name: "fa_times"                 ;  character: "\uf00d" ; }
    ListElement { name: "fa_times_circle"          ;  character: "\uf057" ; }
    ListElement { name: "fa_times_circle_o"        ;  character: "\uf05c" ; }
    ListElement { name: "fa_tint"                  ;  character: "\uf043" ; }
    ListElement { name: "fa_toggle_down"           ;  character: "\uf150" ; }
    ListElement { name: "fa_toggle_left"           ;  character: "\uf191" ; }
    ListElement { name: "fa_toggle_right"          ;  character: "\uf152" ; }
    ListElement { name: "fa_toggle_up"             ;  character: "\uf151" ; }
    ListElement { name: "fa_trash_o"               ;  character: "\uf014" ; }
    ListElement { name: "fa_tree"                  ;  character: "\uf1bb" ; }
    ListElement { name: "fa_trello"                ;  character: "\uf181" ; }
    ListElement { name: "fa_trophy"                ;  character: "\uf091" ; }
    ListElement { name: "fa_truck"                 ;  character: "\uf0d1" ; }
    ListElement { name: "fa_try"                   ;  character: "\uf195" ; }
    ListElement { name: "fa_tumblr"                ;  character: "\uf173" ; }
    ListElement { name: "fa_tumblr_square"         ;  character: "\uf174" ; }
    ListElement { name: "fa_turkish_lira"          ;  character: "\uf195" ; }
    ListElement { name: "fa_twitter"               ;  character: "\uf099" ; }
    ListElement { name: "fa_twitter_square"        ;  character: "\uf081" ; }
    ListElement { name: "fa_umbrella"              ;  character: "\uf0e9" ; }
    ListElement { name: "fa_underline"             ;  character: "\uf0cd" ; }
    ListElement { name: "fa_undo"                  ;  character: "\uf0e2" ; }
    ListElement { name: "fa_university"            ;  character: "\uf19c" ; }
    ListElement { name: "fa_unlink"                ;  character: "\uf127" ; }
    ListElement { name: "fa_unlock"                ;  character: "\uf09c" ; }
    ListElement { name: "fa_unlock_alt"            ;  character: "\uf13e" ; }
    ListElement { name: "fa_unsorted"              ;  character: "\uf0dc" ; }
    ListElement { name: "fa_upload"                ;  character: "\uf093" ; }
    ListElement { name: "fa_usd"                   ;  character: "\uf155" ; }
    ListElement { name: "fa_user"                  ;  character: "\uf007" ; }
    ListElement { name: "fa_user_md"               ;  character: "\uf0f0" ; }
    ListElement { name: "fa_users"                 ;  character: "\uf0c0" ; }
    ListElement { name: "fa_video_camera"          ;  character: "\uf03d" ; }
    ListElement { name: "fa_vimeo_square"          ;  character: "\uf194" ; }
    ListElement { name: "fa_vine"                  ;  character: "\uf1ca" ; }
    ListElement { name: "fa_vk"                    ;  character: "\uf189" ; }
    ListElement { name: "fa_volume_down"           ;  character: "\uf027" ; }
    ListElement { name: "fa_volume_off"            ;  character: "\uf026" ; }
    ListElement { name: "fa_volume_up"             ;  character: "\uf028" ; }
    ListElement { name: "fa_warning"               ;  character: "\uf071" ; }
    ListElement { name: "fa_wechat"                ;  character: "\uf1d7" ; }
    ListElement { name: "fa_weibo"                 ;  character: "\uf18a" ; }
    ListElement { name: "fa_weixin"                ;  character: "\uf1d7" ; }
    ListElement { name: "fa_wheelchair"            ;  character: "\uf193" ; }
    ListElement { name: "fa_windows"               ;  character: "\uf17a" ; }
    ListElement { name: "fa_won"                   ;  character: "\uf159" ; }
    ListElement { name: "fa_wordpress"             ;  character: "\uf19a" ; }
    ListElement { name: "fa_wrench"                ;  character: "\uf0ad" ; }
    ListElement { name: "fa_xing"                  ;  character: "\uf168" ; }
    ListElement { name: "fa_xing_square"           ;  character: "\uf169" ; }
    ListElement { name: "fa_yahoo"                 ;  character: "\uf19e" ; }
    ListElement { name: "fa_yen"                   ;  character: "\uf157" ; }
    ListElement { name: "fa_youtube"               ;  character: "\uf167" ; }
    ListElement { name: "fa_youtube_play"          ;  character: "\uf16a" ; }
    ListElement { name: "fa_youtube_square"        ;  character: "\uf166" ; }
}
